/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
#include <m8c.h>
// AnalogColumn_InputMUX_0 address and mask defines
#pragma	ioport	AnalogColumn_InputMUX_0_Data_ADDR:	0x0
BYTE			AnalogColumn_InputMUX_0_Data_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_0_DriveMode_0_ADDR:	0x100
BYTE			AnalogColumn_InputMUX_0_DriveMode_0_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_0_DriveMode_1_ADDR:	0x101
BYTE			AnalogColumn_InputMUX_0_DriveMode_1_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_0_DriveMode_2_ADDR:	0x3
BYTE			AnalogColumn_InputMUX_0_DriveMode_2_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_0_GlobalSelect_ADDR:	0x2
BYTE			AnalogColumn_InputMUX_0_GlobalSelect_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_0_IntCtrl_0_ADDR:	0x102
BYTE			AnalogColumn_InputMUX_0_IntCtrl_0_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_0_IntCtrl_1_ADDR:	0x103
BYTE			AnalogColumn_InputMUX_0_IntCtrl_1_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_0_IntEn_ADDR:	0x1
BYTE			AnalogColumn_InputMUX_0_IntEn_ADDR;
#define AnalogColumn_InputMUX_0_MASK 0x2
// AnalogColumn_InputMUX_0 Shadow defines
//   AnalogColumn_InputMUX_0_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define AnalogColumn_InputMUX_0_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// AnalogOutBuf_0 address and mask defines
#pragma	ioport	AnalogOutBuf_0_Data_ADDR:	0x0
BYTE			AnalogOutBuf_0_Data_ADDR;
#pragma	ioport	AnalogOutBuf_0_DriveMode_0_ADDR:	0x100
BYTE			AnalogOutBuf_0_DriveMode_0_ADDR;
#pragma	ioport	AnalogOutBuf_0_DriveMode_1_ADDR:	0x101
BYTE			AnalogOutBuf_0_DriveMode_1_ADDR;
#pragma	ioport	AnalogOutBuf_0_DriveMode_2_ADDR:	0x3
BYTE			AnalogOutBuf_0_DriveMode_2_ADDR;
#pragma	ioport	AnalogOutBuf_0_GlobalSelect_ADDR:	0x2
BYTE			AnalogOutBuf_0_GlobalSelect_ADDR;
#pragma	ioport	AnalogOutBuf_0_IntCtrl_0_ADDR:	0x102
BYTE			AnalogOutBuf_0_IntCtrl_0_ADDR;
#pragma	ioport	AnalogOutBuf_0_IntCtrl_1_ADDR:	0x103
BYTE			AnalogOutBuf_0_IntCtrl_1_ADDR;
#pragma	ioport	AnalogOutBuf_0_IntEn_ADDR:	0x1
BYTE			AnalogOutBuf_0_IntEn_ADDR;
#define AnalogOutBuf_0_MASK 0x8
// AnalogOutBuf_0 Shadow defines
//   AnalogOutBuf_0_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define AnalogOutBuf_0_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// LEDPin address and mask defines
#pragma	ioport	LEDPin_Data_ADDR:	0x0
BYTE			LEDPin_Data_ADDR;
#pragma	ioport	LEDPin_DriveMode_0_ADDR:	0x100
BYTE			LEDPin_DriveMode_0_ADDR;
#pragma	ioport	LEDPin_DriveMode_1_ADDR:	0x101
BYTE			LEDPin_DriveMode_1_ADDR;
#pragma	ioport	LEDPin_DriveMode_2_ADDR:	0x3
BYTE			LEDPin_DriveMode_2_ADDR;
#pragma	ioport	LEDPin_GlobalSelect_ADDR:	0x2
BYTE			LEDPin_GlobalSelect_ADDR;
#pragma	ioport	LEDPin_IntCtrl_0_ADDR:	0x102
BYTE			LEDPin_IntCtrl_0_ADDR;
#pragma	ioport	LEDPin_IntCtrl_1_ADDR:	0x103
BYTE			LEDPin_IntCtrl_1_ADDR;
#pragma	ioport	LEDPin_IntEn_ADDR:	0x1
BYTE			LEDPin_IntEn_ADDR;
#define LEDPin_MASK 0x80
// LEDPin Shadow defines
//   LEDPin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LEDPin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
