//*****************************************************************************
//*****************************************************************************
//  FILENAME:  SCBLOCK_1.h  ( SCBLOCK )
//  Version: 2.4, Updated on 2009/10/15 at 17:11:37
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION:  SCBLOCK User Module C Language interface file.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <M8C.h>

//-------------------------------------------------
// Constants for SCBLOCK_1 API's.
//-------------------------------------------------
#define SCBLOCK_1_OFF         0
#define SCBLOCK_1_LOWPOWER    1
#define SCBLOCK_1_MEDPOWER    2
#define SCBLOCK_1_HIGHPOWER   3

#pragma fastcall16 SCBLOCK_1_Start
#pragma fastcall16 SCBLOCK_1_SetPower
#pragma fastcall16 SCBLOCK_1_Stop

//-------------------------------------------------
// Prototypes of the SCBLOCK_1 API.
//-------------------------------------------------
extern void SCBLOCK_1_Start(BYTE bPower);
extern void SCBLOCK_1_SetPower(BYTE bPower);
extern void SCBLOCK_1_Stop(void);

//-------------------------------------------------
// Register Addresses for SCBLOCK_1
//-------------------------------------------------
#pragma ioport  SCBLOCK_1_cr0:  0x088
BYTE            SCBLOCK_1_cr0;
#pragma ioport  SCBLOCK_1_cr1:  0x089
BYTE            SCBLOCK_1_cr1;
#pragma ioport  SCBLOCK_1_cr2:  0x08a
BYTE            SCBLOCK_1_cr2;
#pragma ioport  SCBLOCK_1_cr3:  0x08b
BYTE            SCBLOCK_1_cr3;
#pragma ioport  SCBLOCK_1_Comp_Ctrl:    0x000
BYTE            SCBLOCK_1_Comp_Ctrl;

// end of file SCBLOCK_1.h
