/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Control_Reg_NextStep.h"
#include "Control_Reg_Clock.h"
#include "Status_Reg_CurrentStep.h"
#include "Status_Reg_LastStep.h"
#include "Status_Reg_Error.h"
#include "pantallaLCD.h"
#include "nex_aliases.h"
#include "nex.h"
#include "cross_aliases.h"
#include "cross.h"
#include "pantallaLCD_LCDPort_aliases.h"
#include "pantallaLCD_LCDPort.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

