#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include "cydevice.h"
#include "cydevice_trm.h"

/* nex */
#define nex__0__INTTYPE CYREG_PICU1_INTTYPE7
#define nex__0__MASK 0x80u
#define nex__0__PC CYREG_PRT1_PC7
#define nex__0__PORT 1u
#define nex__0__SHIFT 7u
#define nex__AG CYREG_PRT1_AG
#define nex__AMUX CYREG_PRT1_AMUX
#define nex__BIE CYREG_PRT1_BIE
#define nex__BIT_MASK CYREG_PRT1_BIT_MASK
#define nex__BYP CYREG_PRT1_BYP
#define nex__CTL CYREG_PRT1_CTL
#define nex__DM0 CYREG_PRT1_DM0
#define nex__DM1 CYREG_PRT1_DM1
#define nex__DM2 CYREG_PRT1_DM2
#define nex__DR CYREG_PRT1_DR
#define nex__INP_DIS CYREG_PRT1_INP_DIS
#define nex__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU1_BASE
#define nex__LCD_COM_SEG CYREG_PRT1_LCD_COM_SEG
#define nex__LCD_EN CYREG_PRT1_LCD_EN
#define nex__MASK 0x80u
#define nex__PORT 1u
#define nex__PRT CYREG_PRT1_PRT
#define nex__PRTDSI__CAPS_SEL CYREG_PRT1_CAPS_SEL
#define nex__PRTDSI__DBL_SYNC_IN CYREG_PRT1_DBL_SYNC_IN
#define nex__PRTDSI__OE_SEL0 CYREG_PRT1_OE_SEL0
#define nex__PRTDSI__OE_SEL1 CYREG_PRT1_OE_SEL1
#define nex__PRTDSI__OUT_SEL0 CYREG_PRT1_OUT_SEL0
#define nex__PRTDSI__OUT_SEL1 CYREG_PRT1_OUT_SEL1
#define nex__PRTDSI__SYNC_OUT CYREG_PRT1_SYNC_OUT
#define nex__PS CYREG_PRT1_PS
#define nex__SHIFT 7u
#define nex__SLW CYREG_PRT1_SLW

/* cross */
#define cross__0__INTTYPE CYREG_PICU2_INTTYPE7
#define cross__0__MASK 0x80u
#define cross__0__PC CYREG_PRT2_PC7
#define cross__0__PORT 2u
#define cross__0__SHIFT 7u
#define cross__AG CYREG_PRT2_AG
#define cross__AMUX CYREG_PRT2_AMUX
#define cross__BIE CYREG_PRT2_BIE
#define cross__BIT_MASK CYREG_PRT2_BIT_MASK
#define cross__BYP CYREG_PRT2_BYP
#define cross__CTL CYREG_PRT2_CTL
#define cross__DM0 CYREG_PRT2_DM0
#define cross__DM1 CYREG_PRT2_DM1
#define cross__DM2 CYREG_PRT2_DM2
#define cross__DR CYREG_PRT2_DR
#define cross__INP_DIS CYREG_PRT2_INP_DIS
#define cross__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU2_BASE
#define cross__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define cross__LCD_EN CYREG_PRT2_LCD_EN
#define cross__MASK 0x80u
#define cross__PORT 2u
#define cross__PRT CYREG_PRT2_PRT
#define cross__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define cross__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define cross__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define cross__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define cross__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define cross__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define cross__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define cross__PS CYREG_PRT2_PS
#define cross__SHIFT 7u
#define cross__SLW CYREG_PRT2_SLW

/* pantallaLCD_LCDPort */
#define pantallaLCD_LCDPort__0__INTTYPE CYREG_PICU2_INTTYPE0
#define pantallaLCD_LCDPort__0__MASK 0x01u
#define pantallaLCD_LCDPort__0__PC CYREG_PRT2_PC0
#define pantallaLCD_LCDPort__0__PORT 2u
#define pantallaLCD_LCDPort__0__SHIFT 0u
#define pantallaLCD_LCDPort__1__INTTYPE CYREG_PICU2_INTTYPE1
#define pantallaLCD_LCDPort__1__MASK 0x02u
#define pantallaLCD_LCDPort__1__PC CYREG_PRT2_PC1
#define pantallaLCD_LCDPort__1__PORT 2u
#define pantallaLCD_LCDPort__1__SHIFT 1u
#define pantallaLCD_LCDPort__2__INTTYPE CYREG_PICU2_INTTYPE2
#define pantallaLCD_LCDPort__2__MASK 0x04u
#define pantallaLCD_LCDPort__2__PC CYREG_PRT2_PC2
#define pantallaLCD_LCDPort__2__PORT 2u
#define pantallaLCD_LCDPort__2__SHIFT 2u
#define pantallaLCD_LCDPort__3__INTTYPE CYREG_PICU2_INTTYPE3
#define pantallaLCD_LCDPort__3__MASK 0x08u
#define pantallaLCD_LCDPort__3__PC CYREG_PRT2_PC3
#define pantallaLCD_LCDPort__3__PORT 2u
#define pantallaLCD_LCDPort__3__SHIFT 3u
#define pantallaLCD_LCDPort__4__INTTYPE CYREG_PICU2_INTTYPE4
#define pantallaLCD_LCDPort__4__MASK 0x10u
#define pantallaLCD_LCDPort__4__PC CYREG_PRT2_PC4
#define pantallaLCD_LCDPort__4__PORT 2u
#define pantallaLCD_LCDPort__4__SHIFT 4u
#define pantallaLCD_LCDPort__5__INTTYPE CYREG_PICU2_INTTYPE5
#define pantallaLCD_LCDPort__5__MASK 0x20u
#define pantallaLCD_LCDPort__5__PC CYREG_PRT2_PC5
#define pantallaLCD_LCDPort__5__PORT 2u
#define pantallaLCD_LCDPort__5__SHIFT 5u
#define pantallaLCD_LCDPort__6__INTTYPE CYREG_PICU2_INTTYPE6
#define pantallaLCD_LCDPort__6__MASK 0x40u
#define pantallaLCD_LCDPort__6__PC CYREG_PRT2_PC6
#define pantallaLCD_LCDPort__6__PORT 2u
#define pantallaLCD_LCDPort__6__SHIFT 6u
#define pantallaLCD_LCDPort__AG CYREG_PRT2_AG
#define pantallaLCD_LCDPort__AMUX CYREG_PRT2_AMUX
#define pantallaLCD_LCDPort__BIE CYREG_PRT2_BIE
#define pantallaLCD_LCDPort__BIT_MASK CYREG_PRT2_BIT_MASK
#define pantallaLCD_LCDPort__BYP CYREG_PRT2_BYP
#define pantallaLCD_LCDPort__CTL CYREG_PRT2_CTL
#define pantallaLCD_LCDPort__DM0 CYREG_PRT2_DM0
#define pantallaLCD_LCDPort__DM1 CYREG_PRT2_DM1
#define pantallaLCD_LCDPort__DM2 CYREG_PRT2_DM2
#define pantallaLCD_LCDPort__DR CYREG_PRT2_DR
#define pantallaLCD_LCDPort__INP_DIS CYREG_PRT2_INP_DIS
#define pantallaLCD_LCDPort__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU2_BASE
#define pantallaLCD_LCDPort__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define pantallaLCD_LCDPort__LCD_EN CYREG_PRT2_LCD_EN
#define pantallaLCD_LCDPort__MASK 0x7Fu
#define pantallaLCD_LCDPort__PORT 2u
#define pantallaLCD_LCDPort__PRT CYREG_PRT2_PRT
#define pantallaLCD_LCDPort__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define pantallaLCD_LCDPort__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define pantallaLCD_LCDPort__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define pantallaLCD_LCDPort__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define pantallaLCD_LCDPort__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define pantallaLCD_LCDPort__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define pantallaLCD_LCDPort__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define pantallaLCD_LCDPort__PS CYREG_PRT2_PS
#define pantallaLCD_LCDPort__SHIFT 0u
#define pantallaLCD_LCDPort__SLW CYREG_PRT2_SLW

/* Status_Reg_Error */
#define Status_Reg_Error_sts_sts_reg__0__MASK 0x01u
#define Status_Reg_Error_sts_sts_reg__0__POS 0
#define Status_Reg_Error_sts_sts_reg__1__MASK 0x02u
#define Status_Reg_Error_sts_sts_reg__1__POS 1
#define Status_Reg_Error_sts_sts_reg__16BIT_STATUS_AUX_CTL_REG CYREG_B0_UDB10_11_ACTL
#define Status_Reg_Error_sts_sts_reg__16BIT_STATUS_REG CYREG_B0_UDB10_11_ST
#define Status_Reg_Error_sts_sts_reg__MASK 0x03u
#define Status_Reg_Error_sts_sts_reg__MASK_REG CYREG_B0_UDB10_MSK
#define Status_Reg_Error_sts_sts_reg__MASK_ST_AUX_CTL_REG CYREG_B0_UDB10_MSK_ACTL
#define Status_Reg_Error_sts_sts_reg__PER_ST_AUX_CTL_REG CYREG_B0_UDB10_MSK_ACTL
#define Status_Reg_Error_sts_sts_reg__STATUS_AUX_CTL_REG CYREG_B0_UDB10_ACTL
#define Status_Reg_Error_sts_sts_reg__STATUS_CNT_REG CYREG_B0_UDB10_ST_CTL
#define Status_Reg_Error_sts_sts_reg__STATUS_CONTROL_REG CYREG_B0_UDB10_ST_CTL
#define Status_Reg_Error_sts_sts_reg__STATUS_REG CYREG_B0_UDB10_ST

/* Control_Reg_Clock */
#define Control_Reg_Clock_Sync_ctrl_reg__0__MASK 0x01u
#define Control_Reg_Clock_Sync_ctrl_reg__0__POS 0
#define Control_Reg_Clock_Sync_ctrl_reg__16BIT_CONTROL_AUX_CTL_REG CYREG_B0_UDB10_11_ACTL
#define Control_Reg_Clock_Sync_ctrl_reg__16BIT_CONTROL_CONTROL_REG CYREG_B0_UDB10_11_CTL
#define Control_Reg_Clock_Sync_ctrl_reg__16BIT_CONTROL_COUNT_REG CYREG_B0_UDB10_11_CTL
#define Control_Reg_Clock_Sync_ctrl_reg__16BIT_COUNT_CONTROL_REG CYREG_B0_UDB10_11_CTL
#define Control_Reg_Clock_Sync_ctrl_reg__16BIT_COUNT_COUNT_REG CYREG_B0_UDB10_11_CTL
#define Control_Reg_Clock_Sync_ctrl_reg__16BIT_MASK_MASK_REG CYREG_B0_UDB10_11_MSK
#define Control_Reg_Clock_Sync_ctrl_reg__16BIT_MASK_PERIOD_REG CYREG_B0_UDB10_11_MSK
#define Control_Reg_Clock_Sync_ctrl_reg__16BIT_PERIOD_MASK_REG CYREG_B0_UDB10_11_MSK
#define Control_Reg_Clock_Sync_ctrl_reg__16BIT_PERIOD_PERIOD_REG CYREG_B0_UDB10_11_MSK
#define Control_Reg_Clock_Sync_ctrl_reg__CONTROL_AUX_CTL_REG CYREG_B0_UDB10_ACTL
#define Control_Reg_Clock_Sync_ctrl_reg__CONTROL_REG CYREG_B0_UDB10_CTL
#define Control_Reg_Clock_Sync_ctrl_reg__CONTROL_ST_REG CYREG_B0_UDB10_ST_CTL
#define Control_Reg_Clock_Sync_ctrl_reg__COUNT_REG CYREG_B0_UDB10_CTL
#define Control_Reg_Clock_Sync_ctrl_reg__COUNT_ST_REG CYREG_B0_UDB10_ST_CTL
#define Control_Reg_Clock_Sync_ctrl_reg__MASK 0x01u
#define Control_Reg_Clock_Sync_ctrl_reg__MASK_CTL_AUX_CTL_REG CYREG_B0_UDB10_MSK_ACTL
#define Control_Reg_Clock_Sync_ctrl_reg__PER_CTL_AUX_CTL_REG CYREG_B0_UDB10_MSK_ACTL
#define Control_Reg_Clock_Sync_ctrl_reg__PERIOD_REG CYREG_B0_UDB10_MSK

/* Status_Reg_LastStep */
#define Status_Reg_LastStep_sts_sts_reg__0__MASK 0x01u
#define Status_Reg_LastStep_sts_sts_reg__0__POS 0
#define Status_Reg_LastStep_sts_sts_reg__1__MASK 0x02u
#define Status_Reg_LastStep_sts_sts_reg__1__POS 1
#define Status_Reg_LastStep_sts_sts_reg__16BIT_STATUS_AUX_CTL_REG CYREG_B0_UDB12_13_ACTL
#define Status_Reg_LastStep_sts_sts_reg__16BIT_STATUS_REG CYREG_B0_UDB12_13_ST
#define Status_Reg_LastStep_sts_sts_reg__2__MASK 0x04u
#define Status_Reg_LastStep_sts_sts_reg__2__POS 2
#define Status_Reg_LastStep_sts_sts_reg__3__MASK 0x08u
#define Status_Reg_LastStep_sts_sts_reg__3__POS 3
#define Status_Reg_LastStep_sts_sts_reg__MASK 0x0Fu
#define Status_Reg_LastStep_sts_sts_reg__MASK_REG CYREG_B0_UDB12_MSK
#define Status_Reg_LastStep_sts_sts_reg__STATUS_AUX_CTL_REG CYREG_B0_UDB12_ACTL
#define Status_Reg_LastStep_sts_sts_reg__STATUS_REG CYREG_B0_UDB12_ST

/* Control_Reg_NextStep */
#define Control_Reg_NextStep_Sync_ctrl_reg__0__MASK 0x01u
#define Control_Reg_NextStep_Sync_ctrl_reg__0__POS 0
#define Control_Reg_NextStep_Sync_ctrl_reg__1__MASK 0x02u
#define Control_Reg_NextStep_Sync_ctrl_reg__1__POS 1
#define Control_Reg_NextStep_Sync_ctrl_reg__16BIT_CONTROL_AUX_CTL_REG CYREG_B0_UDB11_12_ACTL
#define Control_Reg_NextStep_Sync_ctrl_reg__16BIT_CONTROL_CONTROL_REG CYREG_B0_UDB11_12_CTL
#define Control_Reg_NextStep_Sync_ctrl_reg__16BIT_CONTROL_COUNT_REG CYREG_B0_UDB11_12_CTL
#define Control_Reg_NextStep_Sync_ctrl_reg__16BIT_COUNT_CONTROL_REG CYREG_B0_UDB11_12_CTL
#define Control_Reg_NextStep_Sync_ctrl_reg__16BIT_COUNT_COUNT_REG CYREG_B0_UDB11_12_CTL
#define Control_Reg_NextStep_Sync_ctrl_reg__16BIT_MASK_MASK_REG CYREG_B0_UDB11_12_MSK
#define Control_Reg_NextStep_Sync_ctrl_reg__16BIT_MASK_PERIOD_REG CYREG_B0_UDB11_12_MSK
#define Control_Reg_NextStep_Sync_ctrl_reg__16BIT_PERIOD_MASK_REG CYREG_B0_UDB11_12_MSK
#define Control_Reg_NextStep_Sync_ctrl_reg__16BIT_PERIOD_PERIOD_REG CYREG_B0_UDB11_12_MSK
#define Control_Reg_NextStep_Sync_ctrl_reg__2__MASK 0x04u
#define Control_Reg_NextStep_Sync_ctrl_reg__2__POS 2
#define Control_Reg_NextStep_Sync_ctrl_reg__3__MASK 0x08u
#define Control_Reg_NextStep_Sync_ctrl_reg__3__POS 3
#define Control_Reg_NextStep_Sync_ctrl_reg__CONTROL_AUX_CTL_REG CYREG_B0_UDB11_ACTL
#define Control_Reg_NextStep_Sync_ctrl_reg__CONTROL_REG CYREG_B0_UDB11_CTL
#define Control_Reg_NextStep_Sync_ctrl_reg__CONTROL_ST_REG CYREG_B0_UDB11_ST_CTL
#define Control_Reg_NextStep_Sync_ctrl_reg__COUNT_REG CYREG_B0_UDB11_CTL
#define Control_Reg_NextStep_Sync_ctrl_reg__COUNT_ST_REG CYREG_B0_UDB11_ST_CTL
#define Control_Reg_NextStep_Sync_ctrl_reg__MASK 0x0Fu
#define Control_Reg_NextStep_Sync_ctrl_reg__MASK_CTL_AUX_CTL_REG CYREG_B0_UDB11_MSK_ACTL
#define Control_Reg_NextStep_Sync_ctrl_reg__PER_CTL_AUX_CTL_REG CYREG_B0_UDB11_MSK_ACTL
#define Control_Reg_NextStep_Sync_ctrl_reg__PERIOD_REG CYREG_B0_UDB11_MSK

/* Status_Reg_CurrentStep */
#define Status_Reg_CurrentStep_sts_sts_reg__0__MASK 0x01u
#define Status_Reg_CurrentStep_sts_sts_reg__0__POS 0
#define Status_Reg_CurrentStep_sts_sts_reg__1__MASK 0x02u
#define Status_Reg_CurrentStep_sts_sts_reg__1__POS 1
#define Status_Reg_CurrentStep_sts_sts_reg__16BIT_STATUS_AUX_CTL_REG CYREG_B0_UDB11_12_ACTL
#define Status_Reg_CurrentStep_sts_sts_reg__16BIT_STATUS_REG CYREG_B0_UDB11_12_ST
#define Status_Reg_CurrentStep_sts_sts_reg__2__MASK 0x04u
#define Status_Reg_CurrentStep_sts_sts_reg__2__POS 2
#define Status_Reg_CurrentStep_sts_sts_reg__3__MASK 0x08u
#define Status_Reg_CurrentStep_sts_sts_reg__3__POS 3
#define Status_Reg_CurrentStep_sts_sts_reg__MASK 0x0Fu
#define Status_Reg_CurrentStep_sts_sts_reg__MASK_REG CYREG_B0_UDB11_MSK
#define Status_Reg_CurrentStep_sts_sts_reg__MASK_ST_AUX_CTL_REG CYREG_B0_UDB11_MSK_ACTL
#define Status_Reg_CurrentStep_sts_sts_reg__PER_ST_AUX_CTL_REG CYREG_B0_UDB11_MSK_ACTL
#define Status_Reg_CurrentStep_sts_sts_reg__STATUS_AUX_CTL_REG CYREG_B0_UDB11_ACTL
#define Status_Reg_CurrentStep_sts_sts_reg__STATUS_CNT_REG CYREG_B0_UDB11_ST_CTL
#define Status_Reg_CurrentStep_sts_sts_reg__STATUS_CONTROL_REG CYREG_B0_UDB11_ST_CTL
#define Status_Reg_CurrentStep_sts_sts_reg__STATUS_REG CYREG_B0_UDB11_ST

/* Miscellaneous */
#define BCLK__BUS_CLK__HZ 24000000U
#define BCLK__BUS_CLK__KHZ 24000U
#define BCLK__BUS_CLK__MHZ 24U
#define CY_PROJECT_NAME "Practica2Parte5"
#define CY_VERSION "PSoC Creator  4.0 Update 1"
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PSOC4A 12u
#define CYDEV_CHIP_DIE_PSOC5LP 19u
#define CYDEV_CHIP_DIE_PSOC5TM 20u
#define CYDEV_CHIP_DIE_TMA4 2u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_FM0P 4u
#define CYDEV_CHIP_FAMILY_FM3 5u
#define CYDEV_CHIP_FAMILY_FM4 6u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC5
#define CYDEV_CHIP_JTAG_ID 0x2E123069u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_4A 12u
#define CYDEV_CHIP_MEMBER_4C 18u
#define CYDEV_CHIP_MEMBER_4D 8u
#define CYDEV_CHIP_MEMBER_4E 4u
#define CYDEV_CHIP_MEMBER_4F 13u
#define CYDEV_CHIP_MEMBER_4G 2u
#define CYDEV_CHIP_MEMBER_4H 11u
#define CYDEV_CHIP_MEMBER_4I 17u
#define CYDEV_CHIP_MEMBER_4J 9u
#define CYDEV_CHIP_MEMBER_4K 10u
#define CYDEV_CHIP_MEMBER_4L 16u
#define CYDEV_CHIP_MEMBER_4M 15u
#define CYDEV_CHIP_MEMBER_4N 6u
#define CYDEV_CHIP_MEMBER_4O 5u
#define CYDEV_CHIP_MEMBER_4P 14u
#define CYDEV_CHIP_MEMBER_4Q 7u
#define CYDEV_CHIP_MEMBER_4U 3u
#define CYDEV_CHIP_MEMBER_5A 20u
#define CYDEV_CHIP_MEMBER_5B 19u
#define CYDEV_CHIP_MEMBER_FM3 24u
#define CYDEV_CHIP_MEMBER_FM4 25u
#define CYDEV_CHIP_MEMBER_PDL_FM0P_TYPE1 21u
#define CYDEV_CHIP_MEMBER_PDL_FM0P_TYPE2 22u
#define CYDEV_CHIP_MEMBER_PDL_FM0P_TYPE3 23u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_5B
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_MEMBER_USED
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PSOC4A_ES0 17u
#define CYDEV_CHIP_REV_PSOC4A_PRODUCTION 17u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REV_PSOC5TM_ES0 0u
#define CYDEV_CHIP_REV_PSOC5TM_ES1 1u
#define CYDEV_CHIP_REV_PSOC5TM_PRODUCTION 1u
#define CYDEV_CHIP_REV_TMA4_ES 17u
#define CYDEV_CHIP_REV_TMA4_ES2 33u
#define CYDEV_CHIP_REV_TMA4_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_4A_ES0 17u
#define CYDEV_CHIP_REVISION_4A_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4C_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4D_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4E_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256DMA 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256K 0u
#define CYDEV_CHIP_REVISION_4G_ES 17u
#define CYDEV_CHIP_REVISION_4G_ES2 33u
#define CYDEV_CHIP_REVISION_4G_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4H_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4I_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4J_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4K_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4L_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4M_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4N_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4O_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4P_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4Q_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4U_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_FM3_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_FM4_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_PDL_FM0P_TYPE1_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_PDL_FM0P_TYPE2_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_PDL_FM0P_TYPE3_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_5B_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REVISION_USED
#define CYDEV_CONFIG_FASTBOOT_ENABLED 1
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowButWarn
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_DMA 0
#define CYDEV_CONFIGURATION_ECC 1
#define CYDEV_CONFIGURATION_IMOENABLED CYDEV_CONFIG_FASTBOOT_ENABLED
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_DEBUG_ENABLE_MASK 0x20u
#define CYDEV_DEBUG_ENABLE_REGISTER CYREG_MLOGIC_DEBUG
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS_JTAG_4 1
#define CYDEV_DEBUGGING_DPS_JTAG_5 0
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_DPS_SWD_SWV 6
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_SWD_SWV
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_DEBUGGING_XRES 0
#define CYDEV_DMA_CHANNELS_AVAILABLE 24u
#define CYDEV_ECC_ENABLE 0
#define CYDEV_HEAP_SIZE 0x80
#define CYDEV_INSTRUCT_CACHE_ENABLED 1
#define CYDEV_INTR_RISING 0x00000000u
#define CYDEV_IS_EXPORTING_CODE 0
#define CYDEV_IS_IMPORTING_CODE 0
#define CYDEV_PROJ_TYPE 0
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LAUNCHER 5
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_LOADABLEANDBOOTLOADER 4
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_PROTECTION_ENABLE 0
#define CYDEV_STACK_SIZE 0x0800
#define CYDEV_USE_BUNDLED_CMSIS 1
#define CYDEV_VARIABLE_VDDA 0
#define CYDEV_VDDA 5.0
#define CYDEV_VDDA_MV 5000
#define CYDEV_VDDD 5.0
#define CYDEV_VDDD_MV 5000
#define CYDEV_VDDIO0 5.0
#define CYDEV_VDDIO0_MV 5000
#define CYDEV_VDDIO1 5.0
#define CYDEV_VDDIO1_MV 5000
#define CYDEV_VDDIO2 5.0
#define CYDEV_VDDIO2_MV 5000
#define CYDEV_VDDIO3 5.0
#define CYDEV_VDDIO3_MV 5000
#define CYDEV_VIO0 5.0
#define CYDEV_VIO0_MV 5000
#define CYDEV_VIO1 5.0
#define CYDEV_VIO1_MV 5000
#define CYDEV_VIO2 5.0
#define CYDEV_VIO2_MV 5000
#define CYDEV_VIO3 5.0
#define CYDEV_VIO3_MV 5000
#define CYIPBLOCK_ARM_CM3_VERSION 0
#define CYIPBLOCK_P3_ANAIF_VERSION 0
#define CYIPBLOCK_P3_CAN_VERSION 0
#define CYIPBLOCK_P3_CAPSENSE_VERSION 0
#define CYIPBLOCK_P3_COMP_VERSION 0
#define CYIPBLOCK_P3_DECIMATOR_VERSION 0
#define CYIPBLOCK_P3_DFB_VERSION 0
#define CYIPBLOCK_P3_DMA_VERSION 0
#define CYIPBLOCK_P3_DRQ_VERSION 0
#define CYIPBLOCK_P3_DSM_VERSION 0
#define CYIPBLOCK_P3_EMIF_VERSION 0
#define CYIPBLOCK_P3_I2C_VERSION 0
#define CYIPBLOCK_P3_LCD_VERSION 0
#define CYIPBLOCK_P3_LPF_VERSION 0
#define CYIPBLOCK_P3_OPAMP_VERSION 0
#define CYIPBLOCK_P3_PM_VERSION 0
#define CYIPBLOCK_P3_SCCT_VERSION 0
#define CYIPBLOCK_P3_TIMER_VERSION 0
#define CYIPBLOCK_P3_USB_VERSION 0
#define CYIPBLOCK_P3_VIDAC_VERSION 0
#define CYIPBLOCK_P3_VREF_VERSION 0
#define CYIPBLOCK_S8_GPIO_VERSION 0
#define CYIPBLOCK_S8_IRQ_VERSION 0
#define CYIPBLOCK_S8_SAR_VERSION 0
#define CYIPBLOCK_S8_SIO_VERSION 0
#define CYIPBLOCK_S8_UDB_VERSION 0
#define DMA_CHANNELS_USED__MASK0 0x00000000u
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
