/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_1.h"
#include "generadorPulsosPWM.h"
#include "ledHardwarePWM_aliases.h"
#include "ledHardwarePWM.h"
#include "isr_GPIO.h"
#include "ledSoftwareInterrupcionPWM_aliases.h"
#include "ledSoftwareInterrupcionPWM.h"
#include "Timer_1.h"
#include "UART.h"
#include "Pantalla.h"
#include "UART_isr.h"
#include "Tx_1_aliases.h"
#include "Tx_1.h"
#include "UART_IntClock.h"
#include "Pantalla_LCDPort_aliases.h"
#include "Pantalla_LCDPort.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

