#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include "cydevice.h"
#include "cydevice_trm.h"

/* pantallaLCD_LCDPort */
#define pantallaLCD_LCDPort__0__INTTYPE CYREG_PICU2_INTTYPE0
#define pantallaLCD_LCDPort__0__MASK 0x01u
#define pantallaLCD_LCDPort__0__PC CYREG_PRT2_PC0
#define pantallaLCD_LCDPort__0__PORT 2u
#define pantallaLCD_LCDPort__0__SHIFT 0u
#define pantallaLCD_LCDPort__1__INTTYPE CYREG_PICU2_INTTYPE1
#define pantallaLCD_LCDPort__1__MASK 0x02u
#define pantallaLCD_LCDPort__1__PC CYREG_PRT2_PC1
#define pantallaLCD_LCDPort__1__PORT 2u
#define pantallaLCD_LCDPort__1__SHIFT 1u
#define pantallaLCD_LCDPort__2__INTTYPE CYREG_PICU2_INTTYPE2
#define pantallaLCD_LCDPort__2__MASK 0x04u
#define pantallaLCD_LCDPort__2__PC CYREG_PRT2_PC2
#define pantallaLCD_LCDPort__2__PORT 2u
#define pantallaLCD_LCDPort__2__SHIFT 2u
#define pantallaLCD_LCDPort__3__INTTYPE CYREG_PICU2_INTTYPE3
#define pantallaLCD_LCDPort__3__MASK 0x08u
#define pantallaLCD_LCDPort__3__PC CYREG_PRT2_PC3
#define pantallaLCD_LCDPort__3__PORT 2u
#define pantallaLCD_LCDPort__3__SHIFT 3u
#define pantallaLCD_LCDPort__4__INTTYPE CYREG_PICU2_INTTYPE4
#define pantallaLCD_LCDPort__4__MASK 0x10u
#define pantallaLCD_LCDPort__4__PC CYREG_PRT2_PC4
#define pantallaLCD_LCDPort__4__PORT 2u
#define pantallaLCD_LCDPort__4__SHIFT 4u
#define pantallaLCD_LCDPort__5__INTTYPE CYREG_PICU2_INTTYPE5
#define pantallaLCD_LCDPort__5__MASK 0x20u
#define pantallaLCD_LCDPort__5__PC CYREG_PRT2_PC5
#define pantallaLCD_LCDPort__5__PORT 2u
#define pantallaLCD_LCDPort__5__SHIFT 5u
#define pantallaLCD_LCDPort__6__INTTYPE CYREG_PICU2_INTTYPE6
#define pantallaLCD_LCDPort__6__MASK 0x40u
#define pantallaLCD_LCDPort__6__PC CYREG_PRT2_PC6
#define pantallaLCD_LCDPort__6__PORT 2u
#define pantallaLCD_LCDPort__6__SHIFT 6u
#define pantallaLCD_LCDPort__AG CYREG_PRT2_AG
#define pantallaLCD_LCDPort__AMUX CYREG_PRT2_AMUX
#define pantallaLCD_LCDPort__BIE CYREG_PRT2_BIE
#define pantallaLCD_LCDPort__BIT_MASK CYREG_PRT2_BIT_MASK
#define pantallaLCD_LCDPort__BYP CYREG_PRT2_BYP
#define pantallaLCD_LCDPort__CTL CYREG_PRT2_CTL
#define pantallaLCD_LCDPort__DM0 CYREG_PRT2_DM0
#define pantallaLCD_LCDPort__DM1 CYREG_PRT2_DM1
#define pantallaLCD_LCDPort__DM2 CYREG_PRT2_DM2
#define pantallaLCD_LCDPort__DR CYREG_PRT2_DR
#define pantallaLCD_LCDPort__INP_DIS CYREG_PRT2_INP_DIS
#define pantallaLCD_LCDPort__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU2_BASE
#define pantallaLCD_LCDPort__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define pantallaLCD_LCDPort__LCD_EN CYREG_PRT2_LCD_EN
#define pantallaLCD_LCDPort__MASK 0x7Fu
#define pantallaLCD_LCDPort__PORT 2u
#define pantallaLCD_LCDPort__PRT CYREG_PRT2_PRT
#define pantallaLCD_LCDPort__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define pantallaLCD_LCDPort__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define pantallaLCD_LCDPort__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define pantallaLCD_LCDPort__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define pantallaLCD_LCDPort__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define pantallaLCD_LCDPort__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define pantallaLCD_LCDPort__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define pantallaLCD_LCDPort__PS CYREG_PRT2_PS
#define pantallaLCD_LCDPort__SHIFT 0u
#define pantallaLCD_LCDPort__SLW CYREG_PRT2_SLW

/* entradaMedicion */
#define entradaMedicion__0__INTTYPE CYREG_PICU1_INTTYPE7
#define entradaMedicion__0__MASK 0x80u
#define entradaMedicion__0__PC CYREG_PRT1_PC7
#define entradaMedicion__0__PORT 1u
#define entradaMedicion__0__SHIFT 7u
#define entradaMedicion__AG CYREG_PRT1_AG
#define entradaMedicion__AMUX CYREG_PRT1_AMUX
#define entradaMedicion__BIE CYREG_PRT1_BIE
#define entradaMedicion__BIT_MASK CYREG_PRT1_BIT_MASK
#define entradaMedicion__BYP CYREG_PRT1_BYP
#define entradaMedicion__CTL CYREG_PRT1_CTL
#define entradaMedicion__DM0 CYREG_PRT1_DM0
#define entradaMedicion__DM1 CYREG_PRT1_DM1
#define entradaMedicion__DM2 CYREG_PRT1_DM2
#define entradaMedicion__DR CYREG_PRT1_DR
#define entradaMedicion__INP_DIS CYREG_PRT1_INP_DIS
#define entradaMedicion__INTTYPE_BASE CYDEV_PICU_INTTYPE_PICU1_BASE
#define entradaMedicion__LCD_COM_SEG CYREG_PRT1_LCD_COM_SEG
#define entradaMedicion__LCD_EN CYREG_PRT1_LCD_EN
#define entradaMedicion__MASK 0x80u
#define entradaMedicion__PORT 1u
#define entradaMedicion__PRT CYREG_PRT1_PRT
#define entradaMedicion__PRTDSI__CAPS_SEL CYREG_PRT1_CAPS_SEL
#define entradaMedicion__PRTDSI__DBL_SYNC_IN CYREG_PRT1_DBL_SYNC_IN
#define entradaMedicion__PRTDSI__OE_SEL0 CYREG_PRT1_OE_SEL0
#define entradaMedicion__PRTDSI__OE_SEL1 CYREG_PRT1_OE_SEL1
#define entradaMedicion__PRTDSI__OUT_SEL0 CYREG_PRT1_OUT_SEL0
#define entradaMedicion__PRTDSI__OUT_SEL1 CYREG_PRT1_OUT_SEL1
#define entradaMedicion__PRTDSI__SYNC_OUT CYREG_PRT1_SYNC_OUT
#define entradaMedicion__PS CYREG_PRT1_PS
#define entradaMedicion__SHIFT 7u
#define entradaMedicion__SLW CYREG_PRT1_SLW

/* convertidorAnalogicoDigital_DEC */
#define convertidorAnalogicoDigital_DEC__COHER CYREG_DEC_COHER
#define convertidorAnalogicoDigital_DEC__CR CYREG_DEC_CR
#define convertidorAnalogicoDigital_DEC__DR1 CYREG_DEC_DR1
#define convertidorAnalogicoDigital_DEC__DR2 CYREG_DEC_DR2
#define convertidorAnalogicoDigital_DEC__DR2H CYREG_DEC_DR2H
#define convertidorAnalogicoDigital_DEC__GCOR CYREG_DEC_GCOR
#define convertidorAnalogicoDigital_DEC__GCORH CYREG_DEC_GCORH
#define convertidorAnalogicoDigital_DEC__GVAL CYREG_DEC_GVAL
#define convertidorAnalogicoDigital_DEC__OCOR CYREG_DEC_OCOR
#define convertidorAnalogicoDigital_DEC__OCORH CYREG_DEC_OCORH
#define convertidorAnalogicoDigital_DEC__OCORM CYREG_DEC_OCORM
#define convertidorAnalogicoDigital_DEC__OUTSAMP CYREG_DEC_OUTSAMP
#define convertidorAnalogicoDigital_DEC__OUTSAMPH CYREG_DEC_OUTSAMPH
#define convertidorAnalogicoDigital_DEC__OUTSAMPM CYREG_DEC_OUTSAMPM
#define convertidorAnalogicoDigital_DEC__OUTSAMPS CYREG_DEC_OUTSAMPS
#define convertidorAnalogicoDigital_DEC__PM_ACT_CFG CYREG_PM_ACT_CFG10
#define convertidorAnalogicoDigital_DEC__PM_ACT_MSK 0x01u
#define convertidorAnalogicoDigital_DEC__PM_STBY_CFG CYREG_PM_STBY_CFG10
#define convertidorAnalogicoDigital_DEC__PM_STBY_MSK 0x01u
#define convertidorAnalogicoDigital_DEC__SHIFT1 CYREG_DEC_SHIFT1
#define convertidorAnalogicoDigital_DEC__SHIFT2 CYREG_DEC_SHIFT2
#define convertidorAnalogicoDigital_DEC__SR CYREG_DEC_SR
#define convertidorAnalogicoDigital_DEC__TRIM__M1 CYREG_FLSHID_CUST_TABLES_DEC_M1
#define convertidorAnalogicoDigital_DEC__TRIM__M2 CYREG_FLSHID_CUST_TABLES_DEC_M2
#define convertidorAnalogicoDigital_DEC__TRIM__M3 CYREG_FLSHID_CUST_TABLES_DEC_M3
#define convertidorAnalogicoDigital_DEC__TRIM__M4 CYREG_FLSHID_CUST_TABLES_DEC_M4
#define convertidorAnalogicoDigital_DEC__TRIM__M5 CYREG_FLSHID_CUST_TABLES_DEC_M5
#define convertidorAnalogicoDigital_DEC__TRIM__M6 CYREG_FLSHID_CUST_TABLES_DEC_M6
#define convertidorAnalogicoDigital_DEC__TRIM__M7 CYREG_FLSHID_CUST_TABLES_DEC_M7
#define convertidorAnalogicoDigital_DEC__TRIM__M8 CYREG_FLSHID_CUST_TABLES_DEC_M8

/* convertidorAnalogicoDigital_DSM */
#define convertidorAnalogicoDigital_DSM__BUF0 CYREG_DSM0_BUF0
#define convertidorAnalogicoDigital_DSM__BUF1 CYREG_DSM0_BUF1
#define convertidorAnalogicoDigital_DSM__BUF2 CYREG_DSM0_BUF2
#define convertidorAnalogicoDigital_DSM__BUF3 CYREG_DSM0_BUF3
#define convertidorAnalogicoDigital_DSM__CLK CYREG_DSM0_CLK
#define convertidorAnalogicoDigital_DSM__CR0 CYREG_DSM0_CR0
#define convertidorAnalogicoDigital_DSM__CR1 CYREG_DSM0_CR1
#define convertidorAnalogicoDigital_DSM__CR10 CYREG_DSM0_CR10
#define convertidorAnalogicoDigital_DSM__CR11 CYREG_DSM0_CR11
#define convertidorAnalogicoDigital_DSM__CR12 CYREG_DSM0_CR12
#define convertidorAnalogicoDigital_DSM__CR13 CYREG_DSM0_CR13
#define convertidorAnalogicoDigital_DSM__CR14 CYREG_DSM0_CR14
#define convertidorAnalogicoDigital_DSM__CR15 CYREG_DSM0_CR15
#define convertidorAnalogicoDigital_DSM__CR16 CYREG_DSM0_CR16
#define convertidorAnalogicoDigital_DSM__CR17 CYREG_DSM0_CR17
#define convertidorAnalogicoDigital_DSM__CR2 CYREG_DSM0_CR2
#define convertidorAnalogicoDigital_DSM__CR3 CYREG_DSM0_CR3
#define convertidorAnalogicoDigital_DSM__CR4 CYREG_DSM0_CR4
#define convertidorAnalogicoDigital_DSM__CR5 CYREG_DSM0_CR5
#define convertidorAnalogicoDigital_DSM__CR6 CYREG_DSM0_CR6
#define convertidorAnalogicoDigital_DSM__CR7 CYREG_DSM0_CR7
#define convertidorAnalogicoDigital_DSM__CR8 CYREG_DSM0_CR8
#define convertidorAnalogicoDigital_DSM__CR9 CYREG_DSM0_CR9
#define convertidorAnalogicoDigital_DSM__DEM0 CYREG_DSM0_DEM0
#define convertidorAnalogicoDigital_DSM__DEM1 CYREG_DSM0_DEM1
#define convertidorAnalogicoDigital_DSM__MISC CYREG_DSM0_MISC
#define convertidorAnalogicoDigital_DSM__OUT0 CYREG_DSM0_OUT0
#define convertidorAnalogicoDigital_DSM__OUT1 CYREG_DSM0_OUT1
#define convertidorAnalogicoDigital_DSM__REF0 CYREG_DSM0_REF0
#define convertidorAnalogicoDigital_DSM__REF1 CYREG_DSM0_REF1
#define convertidorAnalogicoDigital_DSM__REF2 CYREG_DSM0_REF2
#define convertidorAnalogicoDigital_DSM__REF3 CYREG_DSM0_REF3
#define convertidorAnalogicoDigital_DSM__RSVD1 CYREG_DSM0_RSVD1
#define convertidorAnalogicoDigital_DSM__SW0 CYREG_DSM0_SW0
#define convertidorAnalogicoDigital_DSM__SW2 CYREG_DSM0_SW2
#define convertidorAnalogicoDigital_DSM__SW3 CYREG_DSM0_SW3
#define convertidorAnalogicoDigital_DSM__SW4 CYREG_DSM0_SW4
#define convertidorAnalogicoDigital_DSM__SW6 CYREG_DSM0_SW6
#define convertidorAnalogicoDigital_DSM__TR0 CYREG_NPUMP_DSM_TR0
#define convertidorAnalogicoDigital_DSM__TST0 CYREG_DSM0_TST0
#define convertidorAnalogicoDigital_DSM__TST1 CYREG_DSM0_TST1

/* convertidorAnalogicoDigital_Ext_CP_Clk */
#define convertidorAnalogicoDigital_Ext_CP_Clk__CFG0 CYREG_CLKDIST_DCFG0_CFG0
#define convertidorAnalogicoDigital_Ext_CP_Clk__CFG1 CYREG_CLKDIST_DCFG0_CFG1
#define convertidorAnalogicoDigital_Ext_CP_Clk__CFG2 CYREG_CLKDIST_DCFG0_CFG2
#define convertidorAnalogicoDigital_Ext_CP_Clk__CFG2_SRC_SEL_MASK 0x07u
#define convertidorAnalogicoDigital_Ext_CP_Clk__INDEX 0x00u
#define convertidorAnalogicoDigital_Ext_CP_Clk__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define convertidorAnalogicoDigital_Ext_CP_Clk__PM_ACT_MSK 0x01u
#define convertidorAnalogicoDigital_Ext_CP_Clk__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define convertidorAnalogicoDigital_Ext_CP_Clk__PM_STBY_MSK 0x01u

/* convertidorAnalogicoDigital_IRQ */
#define convertidorAnalogicoDigital_IRQ__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define convertidorAnalogicoDigital_IRQ__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define convertidorAnalogicoDigital_IRQ__INTC_MASK 0x20000000u
#define convertidorAnalogicoDigital_IRQ__INTC_NUMBER 29u
#define convertidorAnalogicoDigital_IRQ__INTC_PRIOR_NUM 7u
#define convertidorAnalogicoDigital_IRQ__INTC_PRIOR_REG CYREG_NVIC_PRI_29
#define convertidorAnalogicoDigital_IRQ__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define convertidorAnalogicoDigital_IRQ__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* convertidorAnalogicoDigital_theACLK */
#define convertidorAnalogicoDigital_theACLK__CFG0 CYREG_CLKDIST_ACFG0_CFG0
#define convertidorAnalogicoDigital_theACLK__CFG1 CYREG_CLKDIST_ACFG0_CFG1
#define convertidorAnalogicoDigital_theACLK__CFG2 CYREG_CLKDIST_ACFG0_CFG2
#define convertidorAnalogicoDigital_theACLK__CFG2_SRC_SEL_MASK 0x07u
#define convertidorAnalogicoDigital_theACLK__CFG3 CYREG_CLKDIST_ACFG0_CFG3
#define convertidorAnalogicoDigital_theACLK__CFG3_PHASE_DLY_MASK 0x0Fu
#define convertidorAnalogicoDigital_theACLK__INDEX 0x00u
#define convertidorAnalogicoDigital_theACLK__PM_ACT_CFG CYREG_PM_ACT_CFG1
#define convertidorAnalogicoDigital_theACLK__PM_ACT_MSK 0x01u
#define convertidorAnalogicoDigital_theACLK__PM_STBY_CFG CYREG_PM_STBY_CFG1
#define convertidorAnalogicoDigital_theACLK__PM_STBY_MSK 0x01u

/* Miscellaneous */
#define BCLK__BUS_CLK__HZ 24000000U
#define BCLK__BUS_CLK__KHZ 24000U
#define BCLK__BUS_CLK__MHZ 24U
#define CY_PROJECT_NAME "Practica4Parte1Voltimetro"
#define CY_VERSION "PSoC Creator  4.0 Update 1"
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PSOC4A 12u
#define CYDEV_CHIP_DIE_PSOC5LP 19u
#define CYDEV_CHIP_DIE_PSOC5TM 20u
#define CYDEV_CHIP_DIE_TMA4 2u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_FM0P 4u
#define CYDEV_CHIP_FAMILY_FM3 5u
#define CYDEV_CHIP_FAMILY_FM4 6u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC5
#define CYDEV_CHIP_JTAG_ID 0x2E123069u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_4A 12u
#define CYDEV_CHIP_MEMBER_4C 18u
#define CYDEV_CHIP_MEMBER_4D 8u
#define CYDEV_CHIP_MEMBER_4E 4u
#define CYDEV_CHIP_MEMBER_4F 13u
#define CYDEV_CHIP_MEMBER_4G 2u
#define CYDEV_CHIP_MEMBER_4H 11u
#define CYDEV_CHIP_MEMBER_4I 17u
#define CYDEV_CHIP_MEMBER_4J 9u
#define CYDEV_CHIP_MEMBER_4K 10u
#define CYDEV_CHIP_MEMBER_4L 16u
#define CYDEV_CHIP_MEMBER_4M 15u
#define CYDEV_CHIP_MEMBER_4N 6u
#define CYDEV_CHIP_MEMBER_4O 5u
#define CYDEV_CHIP_MEMBER_4P 14u
#define CYDEV_CHIP_MEMBER_4Q 7u
#define CYDEV_CHIP_MEMBER_4U 3u
#define CYDEV_CHIP_MEMBER_5A 20u
#define CYDEV_CHIP_MEMBER_5B 19u
#define CYDEV_CHIP_MEMBER_FM3 24u
#define CYDEV_CHIP_MEMBER_FM4 25u
#define CYDEV_CHIP_MEMBER_PDL_FM0P_TYPE1 21u
#define CYDEV_CHIP_MEMBER_PDL_FM0P_TYPE2 22u
#define CYDEV_CHIP_MEMBER_PDL_FM0P_TYPE3 23u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_5B
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_MEMBER_USED
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PSOC4A_ES0 17u
#define CYDEV_CHIP_REV_PSOC4A_PRODUCTION 17u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REV_PSOC5TM_ES0 0u
#define CYDEV_CHIP_REV_PSOC5TM_ES1 1u
#define CYDEV_CHIP_REV_PSOC5TM_PRODUCTION 1u
#define CYDEV_CHIP_REV_TMA4_ES 17u
#define CYDEV_CHIP_REV_TMA4_ES2 33u
#define CYDEV_CHIP_REV_TMA4_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_4A_ES0 17u
#define CYDEV_CHIP_REVISION_4A_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4C_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4D_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4E_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256DMA 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256K 0u
#define CYDEV_CHIP_REVISION_4G_ES 17u
#define CYDEV_CHIP_REVISION_4G_ES2 33u
#define CYDEV_CHIP_REVISION_4G_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4H_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4I_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4J_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4K_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4L_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4M_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4N_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4O_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4P_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4Q_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4U_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_FM3_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_FM4_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_PDL_FM0P_TYPE1_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_PDL_FM0P_TYPE2_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_PDL_FM0P_TYPE3_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_5B_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REVISION_USED
#define CYDEV_CONFIG_FASTBOOT_ENABLED 1
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowButWarn
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_DMA 0
#define CYDEV_CONFIGURATION_ECC 1
#define CYDEV_CONFIGURATION_IMOENABLED CYDEV_CONFIG_FASTBOOT_ENABLED
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_DEBUG_ENABLE_MASK 0x20u
#define CYDEV_DEBUG_ENABLE_REGISTER CYREG_MLOGIC_DEBUG
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS_JTAG_4 1
#define CYDEV_DEBUGGING_DPS_JTAG_5 0
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_DPS_SWD_SWV 6
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_SWD_SWV
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_DEBUGGING_XRES 0
#define CYDEV_DMA_CHANNELS_AVAILABLE 24u
#define CYDEV_ECC_ENABLE 0
#define CYDEV_HEAP_SIZE 0x80
#define CYDEV_INSTRUCT_CACHE_ENABLED 1
#define CYDEV_INTR_RISING 0x00000000u
#define CYDEV_IS_EXPORTING_CODE 0
#define CYDEV_IS_IMPORTING_CODE 0
#define CYDEV_PROJ_TYPE 0
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LAUNCHER 5
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_LOADABLEANDBOOTLOADER 4
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_PROTECTION_ENABLE 0
#define CYDEV_STACK_SIZE 0x0800
#define CYDEV_USE_BUNDLED_CMSIS 1
#define CYDEV_VARIABLE_VDDA 0
#define CYDEV_VDDA 5.0
#define CYDEV_VDDA_MV 5000
#define CYDEV_VDDD 5.0
#define CYDEV_VDDD_MV 5000
#define CYDEV_VDDIO0 5.0
#define CYDEV_VDDIO0_MV 5000
#define CYDEV_VDDIO1 5.0
#define CYDEV_VDDIO1_MV 5000
#define CYDEV_VDDIO2 5.0
#define CYDEV_VDDIO2_MV 5000
#define CYDEV_VDDIO3 5.0
#define CYDEV_VDDIO3_MV 5000
#define CYDEV_VIO0 5.0
#define CYDEV_VIO0_MV 5000
#define CYDEV_VIO1 5.0
#define CYDEV_VIO1_MV 5000
#define CYDEV_VIO2 5.0
#define CYDEV_VIO2_MV 5000
#define CYDEV_VIO3 5.0
#define CYDEV_VIO3_MV 5000
#define CYIPBLOCK_ARM_CM3_VERSION 0
#define CYIPBLOCK_P3_ANAIF_VERSION 0
#define CYIPBLOCK_P3_CAN_VERSION 0
#define CYIPBLOCK_P3_CAPSENSE_VERSION 0
#define CYIPBLOCK_P3_COMP_VERSION 0
#define CYIPBLOCK_P3_DECIMATOR_VERSION 0
#define CYIPBLOCK_P3_DFB_VERSION 0
#define CYIPBLOCK_P3_DMA_VERSION 0
#define CYIPBLOCK_P3_DRQ_VERSION 0
#define CYIPBLOCK_P3_DSM_VERSION 0
#define CYIPBLOCK_P3_EMIF_VERSION 0
#define CYIPBLOCK_P3_I2C_VERSION 0
#define CYIPBLOCK_P3_LCD_VERSION 0
#define CYIPBLOCK_P3_LPF_VERSION 0
#define CYIPBLOCK_P3_OPAMP_VERSION 0
#define CYIPBLOCK_P3_PM_VERSION 0
#define CYIPBLOCK_P3_SCCT_VERSION 0
#define CYIPBLOCK_P3_TIMER_VERSION 0
#define CYIPBLOCK_P3_USB_VERSION 0
#define CYIPBLOCK_P3_VIDAC_VERSION 0
#define CYIPBLOCK_P3_VREF_VERSION 0
#define CYIPBLOCK_S8_GPIO_VERSION 0
#define CYIPBLOCK_S8_IRQ_VERSION 0
#define CYIPBLOCK_S8_SAR_VERSION 0
#define CYIPBLOCK_S8_SIO_VERSION 0
#define CYIPBLOCK_S8_UDB_VERSION 0
#define DMA_CHANNELS_USED__MASK0 0x00000000u
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
